apiVersion: v1
kind: Service
metadata:
  name: app-b-dev
  namespace: dev
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: app-b-dev
  sessionAffinity: None
  type: ClusterIP
