apiVersion: v1
kind: Service
metadata:
  name: app-b
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: app-b
  sessionAffinity: None
  type: ClusterIP
