version: "3.9"

networks:
  proxy:
    driver: overlay

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - proxy

  site1:
    image: henrique77/site1:1.0
    networks:
      - proxy

  site2:
    image: henrique77/site2:1.0
    networks:
      - proxy