version: "3.9"

networks:
  docker_compose_proxy:
      driver: overlay
      attachable: true
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - docker_compose_proxy

  site1:
    image: henrique77/site1:2.0
    networks:
      - docker_compose_proxy

  site2:
    image: henrique77/site2:2.0
    networks:
      - docker_compose_proxy