apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cluster-desafio
  region: us-east-1
vpc:
  id: "vpc-0b657e9c8ee8b238c"
  securityGroup: "sg-069fcfaf72c6b00e7"
  sharedNodeSecurityGroup: "sg-069fcfaf72c6b00e7"
  manageSharedNodeSecurityGroupRules: true
  subnets:
    private:
      us-east-1a:
        id: "subnet-09f8c7428eed0f769"
      us-east-1b:
        id: "subnet-0c1f64e7111498cdf"  
managedNodeGroups:
  - name: desafio-ng
    instanceType: t3.medium
    amiFamily: AmazonLinux2
    securityGroups:
      attachIDs: ["sg-069fcfaf72c6b00e7"]
    privateNetworking: true
    volumeSize: 20
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        cloudWatch: true
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

    