apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b 

spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-b
##### Config de Template do Pod ####
  template:
    metadata:
      labels:
        app: app-b
        
#### Config de Specs do Container #####
    spec:
      containers:
        - name: app-b
          image: henrique77/apps:appb
          ports:
          - containerPort: 80
            name: nginx
            protocol: TCP
