apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-app-c

spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-c

##### Config de Template do Pod ####
  template:
    metadata:
      labels:
        app: app-c
        
#### Config de Specs do Container #####
    spec:
      containers:
        - name: app-c
          image: henrique77/apps:appc
          ports:
          - containerPort: 80
            name: nginx
            protocol: TCP
