apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-a
##### Config de Template do Pod ####
  template:
    metadata:
      labels:
        app: app-a
#### Config de Specs do Container #####
    spec:
      containers:
        - name: app-a
          image: henrique77/appa
          ports:
          - containerPort: 80
            name: nginx
            protocol: TCP
