apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-desafio
  region: us-east-1

vpc:
  id: ""
  securityGroup: ""
  sharedNodeSecurityGroup: ""
  manageSharedNodeSecurityGroupRules: true 
  subnets:
    private:
      us-east-1a:
        id: ""
      us-east-1b:
        id: ""

nodeGroups:
  - name: desafio-ng
    instanceType: t2.micro
    amiFamily: AmazonLinux2
    privateNetworking: true
    volumeSize: 20 
    desiredCapacity: 4
    minSize: 2
    maxSize: 6
    iam:
      withAddonPolicies:
        autoscaler: true
        externalDNS: true
        certManager: true
        cloudWatch: true

    