apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-desafio
  region: us-east-1

vpc:
  id: "vpc-0757207cc04da99b0"
  securityGroup: "sg-02d27ddb102f7336c"
  subnets:
    private:
      us-east-1a:
        id: "subnet-047fa000fdcf9e125"
      us-east-1b:
        id: "subnet-0e8b740892bb68bb9"  
managedNodeGroups:
  - name: desafio-ng
    instanceType: t3.medium
    amiFamily: AmazonLinux2
    securityGroups:
      attachIDs: ["sg-02d27ddb102f7336c"]
    privateNetworking: true
    volumeSize: 20
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        cloudWatch: true
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

    